[features]
seeds = true
[programs.localnet]
crypton_donation_charity = "FAJt5bV5epF8fYd9xzv7SqkapN4Bv5dsmvEfKxYYCvro"

[programs.devnet]
crypton_donation_charity = "FAJt5bV5epF8fYd9xzv7SqkapN4Bv5dsmvEfKxYYCvro"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/wubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
